language: node_js
node_js: stable

after_success:
  - ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls

script:
  - npm install
  - npm test
  - npm run build

  deploy:
  provider: heroku
  api_key:
    secure: QGW26G5/soFKWB5n18+grOgGkH6EdFGgJ7xe3amchVyqURNfWu0jO3X1PJhK4W+Gou45X10SxrFYDpZqypt1AZq6h/NoYfnxONzv4Xi42zLsmbaKJ16VgqJWlxB+HG5Tr3nN4srLcY1b6IeG4vhni33TbpANbni84GoAd5JRLruzjJFsHzu9bEm3121ZBi17lanVQSYxyRo1dQPmlBxMtn7zMGRtsWmmgQGaaRQvcOXt40Ej/9J5QVMfwGH4KRotSTWIrffdBuCZgW/nPTqfpfg8UKGwSmlPahxfyk+3Yv9zg7567NK6nDIBeliI0hjZ1ICIiiEt6IS5jldTmDWCsTPqKfAFqok8fkHY/3qBAsWY4CdGeBbhvo7Y/gsobwUqNpr2zCYnVvMhyqes+vBJwz/AyFHWJ4k2gOn5WoVJb9mGDD8LkHEdmnz7BM4FX9g0U6eNrZjpcFv/rg/IO6DPJNTTqex1MQo9v7+7OivJmbPIUjoTSiUERs0fgMFD0P54Jb49Gnn1tKFX8xjjC0fGXQcTaDmgt1NiB2ADoS0H5NQnUZW7fpMT8ZKcv7PY1Bt8zeFMvSoUDi6fmYkA8HZgTqXHO2lzwjUzHS8YfwYbux2QkzHOH4PwQp9cF7AmOTGpjoOC+nz4ShPQ7ReqsfkHHtSrocRiDUaf/CGHUcTcDvY=
  app: react-delayed
  on:
    repo: Wildhoney/ReactDelayed
